### ISSUE TITLE
Restore pre-macOS 26 SDK build compatibility for Apple Speech

### ISSUE THREAD

**Issue by JINGBANZ** [JINGBANZ/jarvis#125]
## Summary

PR #123 adds opt-in Apple Speech transcription using the macOS 26 `SpeechAnalyzer` APIs. The implementation works with the macOS 26 SDK, but the repository's macOS 15 CI runner cannot compile source files that name those newer API types.

This should be handled as a focused compatibility change without changing OpenAI transcription behavior or the macOS 26 Apple Speech data path.

## Evidence

- Related PR: #123
- Failing workflow: https://github.com/JINGBANZ/jarvis/actions/runs/30985871135
- CI environment: macOS 15, Swift 6.1.2
- Representative compiler errors:
  - `cannot find 'SpeechTranscriber' in scope`
  - `cannot find type 'SpeechAnalyzer' in scope`
  - `cannot find type 'AnalyzerInput' in scope`
  - `cannot find 'AssetInventory' in scope`
- The same branch builds on the macOS 26.5 SDK with Swift 6.3.3, and the serialized local suite passes 605 tests across 71 suites.

## Root cause

`@available(macOS 26.0, *)` protects runtime execution, but it does not hide unknown type names from an older SDK/compiler. Every direct reference to the new Speech framework APIs therefore needs a compile-time SDK/toolchain boundary.

Affected areas currently include:

- `AppleSpeechTranscriber`
- `AppleSpeechModelPreparation`
- Apple Speech locale discovery and availability in `APIKeyControls`
- Apple Speech construction in `TranscriptionSessionFactory`

## Proposed implementation

- Compile the real `SpeechAnalyzer` adapter only when the build toolchain exposes the macOS 26 Speech APIs.
- Keep the existing runtime macOS 26 availability checks.
- On older SDKs, compile a small fallback that:
  - reports Apple Speech as unavailable;
  - disables its Settings option and locale discovery;
  - prevents session construction through the existing typed user-facing failure path.
- Keep the shared `TranscriptionSession`, audio-format contract, coaching coordinator, and all OpenAI providers unchanged.
- Add a way to force-build the fallback path with the newer SDK, if practical, so it does not silently bit-rot.

A candidate boundary is a compiler/SDK conditional such as `#if compiler(>=6.2) && canImport(Speech)`, but the implementation should verify the earliest toolchain that actually contains these symbols rather than assuming the version indefinitely.

## Acceptance criteria

- The existing macOS 15 GitHub Actions job compiles and passes.
- A macOS 26 build still exposes and runs the Apple Speech provider.
- On an older SDK/toolchain, Apple Speech is unavailable without affecting OpenAI transcription.
- No macOS 26-only Speech symbol is parsed on the fallback compilation path.
- `swift build` passes.
- `SWT_EXPERIMENTAL_MAXIMUM_PARALLELIZATION_WIDTH=1 ./scripts/run-tests.sh` passes.
- The change lands separately from the provider/refactor implementation.

**Comment by JINGBANZ** [comment]
**Claude finished @JINGBANZ's task in 8m 27s** —— [View job](https://github.com/JINGBANZ/jarvis/actions/runs/30988298760) • [`claude/issue-125-20260805-0816`](https://github.com/JINGBANZ/jarvis/tree/claude/issue-125-20260805-0816) • [Create PR ➔](https://github.com/JINGBANZ/jarvis/compare/main...claude/issue-125-20260805-0816?quick_pull=1&title=Issue%20%23125%3A%20Changes%20from%20Claude&body=This%20PR%20addresses%20issue%20%23125%0A%0AGenerated%20with%20%5BClaude%20Code%5D(https%3A%2F%2Fclaude.ai%2Fcode)

---
### Restore pre-macOS 26 SDK build compatibility for Apple Speech

- [x] Read issue and locate the Apple Speech code (it lives on PR #123's branch, not `main`)
- [x] Map every direct reference to the macOS 26 Speech APIs
- [x] Add a compile-time SDK/toolchain boundary + fallback path
- [x] Verify no macOS 26-only Speech symbol is parsed on the fallback path
- [x] Commit, push, open PR

### What I did

`@available(macOS 26.0, *)` gates *runtime* execution but doesn't hide the new type names (`SpeechAnalyzer`, `SpeechTranscriber`, `AnalyzerInput`, `AssetInventory`) from an older SDK/compiler — so the macOS 15 / Swift 6.1.x CI runner can't compile them. I added a **compile-time** boundary:

| File | Change |
|---|---|
| `Package.swift` | Single source of truth — defines `APPLE_SPEECH_SDK` for `JarvisApp` only when `compiler(>=6.2)` (Xcode 26, the first SDK shipping these symbols). `JARVIS_FORCE_APPLE_SPEECH_FALLBACK=1` force-builds the fallback so it can't bit-rot. |
| `AppleSpeechTranscriber.swift` | Whole `SpeechAnalyzer` adapter wrapped in `#if APPLE_SPEECH_SDK`. |
| `AppleSpeechModelPreparation.swift` | Type + `prepare(...)` signature kept on both paths (so `AppDelegate` links unchanged); Speech body gated, throws the typed *unavailable* failure on older SDKs. |
| `TranscriptionSessionFactory.swift` | Apple Speech construction gated; fallback case unreachable (prep fails first). |
| `APIKeyControls.swift` | Settings locale discovery + availability gated → "Unavailable" and disabled on older SDKs. |

The shared `TranscriptionSession` contract, audio format, coaching coordinator, and all OpenAI providers are untouched.

### Base branch
The Apple Speech code this fix guards exists **only on `feat/apple-speech-transcription` (PR #123)**, not on `main`. The issue asks for this compatibility change to land *separately* from the provider implementation, so **PR #126 targets `feat/apple-speech-transcription`**, not `main`. A PR against `main` would have to re-include all of PR #123.

### Verification
This worker is **Linux, Swift 6.1.3** — i.e. `compiler(<6.2)`, so it compiles the **fallback** path, matching the macOS 15 CI condition. Evidence gathered here:
- `Package.swift` define-machinery parses; `JarvisCore` builds clean.
- A `JarvisApp` build surfaces **zero** Speech-symbol errors — only `AppKit`/`AVFoundation` "no such module" errors, which are inherent to Linux and unrelated to this change.

⚠️ I **cannot** run the full macOS gate here: `swift build` (the AppKit/AVFoundation app target) and `SWT_EXPERIMENTAL_MAXIMUM_PARALLELIZATION_WIDTH=1 ./scripts/run-tests.sh` require macOS. Those acceptance criteria — the macOS 15 job compiling **and** a macOS 26 job still exposing/running the real Apple Speech provider — must be confirmed by the macOS CI on PR #126.

**➡️ [Open PR #126](https://github.com/JINGBANZ/jarvis/pull/126)** (base: `feat/apple-speech-transcription`)
 · branch `claude/issue-125-20260805-0816`
